CREATE TABLE dbo.[Login]
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	UserName NVARCHAR(256) NOT NULL UNIQUE,
	Password NVARCHAR(15) NOT NULL,
	FirstName NVARCHAR(256) NULL,
	LastName NVARCHAR(256) NULL,
	CIty NVARCHAR(100) NULL,
	UserTypeId INT NOT NULL,
	CreatedOn DateTime NOT NULL,

	CONSTRAINT FK_Login_UserType FOREIGN KEY(UserTypeId) REFERENCES dbo.UserType(Id)
)